---
Parameters:
  MyBucketName:
    Type: String
    Default: "default-bucket-name-noureddine247823"
    Description: "Name of the lambda function"

Resources:
  MyS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: "Private"
      BucketName: !Ref MyBucketName